spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/{db}
        username: {user}
        password: {password}
        driver-class-name: org.mariadb.jdbc.Driver

        #        validation query 설정
        tomcat:
            test-on-borrow: true
            validation-query: select 1

    jpa:
        hibernate:
#            ddl-auto: create
            ddl-auto: validate
        properties:
            hibernate:
#                format_sql: true
#                show_sql: true
            default_batch_fetch_size: 1000
        database-platform: org.hibernate.dialect.MariaDBDialect

    redis:
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 2
        host:
        port: 6379
        password:
    session:
        store-type: redis   # 세션 저장소를 지정합니다.
        redis:
            namespace: shopping:session   # 세션을 저장하는 데 사용되는 키의 네임스페이스를 지정합니다.
    # Redis Cache
    cache:
        type: redis

server:
    servlet:
        session:
            cookie:
                path: / # 적용될 URL 경로를 나타냅니다. 예를 들어, path를 "/"로 설정하면 해당 도메인의 모든 경로에서 쿠키가 사용될 수 있습니다.
                name: JSESSIONID # 이름을 지정합니다.
                http-only: true # 브라우저에서 해당 쿠키에 대한 JavaScript 접근을 제한합니다. 이를 통해 XSS 공격을 방지할 수 있습니다.
                secure: true # 쿠키가 HTTPS(SSL/TLS) 연결을 통해서만 전송되어야 함을 나타냅니다. 즉, HTTPS로 암호화된 연결에서만 쿠키가 전송되어야 합니다.
            timeout: 3600 # 세션의 유효 시간을 지정합니다. 단위는 초입니다.

    error:
        include-exception: false # 오류 응답에 exception의 내용을 포함할지 여부
        include-stacktrace: never # 오류 응답에 stacktrace 내용을 포함할 지 여부

    # 톰캣 액세스 로그
    tomcat:
        accesslog:
            enabled: true
            directory: logs
            file-date-format: yyyy-MM-dd
            prefix: access_
            suffix: .log


logging.level:
    org.hibernate.SQL: debug
    #    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework: DEBUG


#    devtools:
#        livereload:
#            enabled: true
    thymeleaf:
#        cache: false
        prefix: classpath:templates/
    web:
        resources:
            static-locations: classpath:static/

    jdbc:       # log4jdbc 설정
        sqlonly: off
        sqltiming: info
        resultsettable: off
        audit: off
        resultset: off
        connection: off

custom:
    account:
        # form
        # keycloak
        type: form
    page:
        intro: /index