spring:
    profiles:
        group:
            local:
                - local
                - actuator

            dev:
                - dev
                - actuator

            prod:
                - prod
                - actuator
---
spring:
    profiles:
        activate:
            on-profile: local

---

spring:
    profiles:
        activate:
            on-profile: dev

---
spring:
    profiles:
        activate:
            on-profile: prod

