spring:
    profiles:
        group:
            local:
                - local
                - custom

            dev:
                - dev

            prod:
                - prod
---
spring:
    profiles:
        activate:
            on-profile: local

---

spring:
    profiles:
        activate:
            on-profile: dev

---
spring:
    profiles:
        activate:
            on-profile: prod

